### ISSUE TITLE
Problem: ascii codes cant decode when the filename contains a backtick

### ISSUE THREAD

**Issue by lwo** [archivematica/Issues#16]
On: Ubuntu 16.04 lts - 64 bit / qa/1.x
we see the following error when the filename contains a backtick: `

```
assignuuidstodirectories_v0.0: INFO      2018-07-16 14:01:12,208  archivematica.mcp.client.assignUUIDsToDirectories.get_dir_uuids:270  Assigning UUID 0258cedb-d6a1-462f-8db1-236dac5c7b25 to directory path %transferDirectory%objects/14 - Silly filenames/folder with a ` grave accent/
'ascii' codec can't decode byte 0xc3 in position 66: ordinal not in range(128)Traceback (most recent call last):
  File "/opt/archivematica/archivematica/src/MCPClient/lib/job.py", line 97, in JobContext
    yield
  File "/opt/archivematica/archivematica/src/MCPClient/lib/clientScripts/assign_uuids_to_directories.py", line 137, in call
    job.set_status(main(job, **vars(args)))
  File "/opt/archivematica/archivematica/src/MCPClient/lib/clientScripts/assign_uuids_to_directories.py", line 67, in wrapped
    func(*_args, **kwargs)
  File "/opt/archivematica/archivematica/src/MCPClient/lib/clientScripts/assign_uuids_to_directories.py", line 119, in main
    _get_transfer_mdl(transfer_uuid))
  File "/usr/share/archivematica/dashboard/main/models.py", line 490, in create_many
    for dir_ in dir_paths_uuids:
  File "/usr/lib/archivematica/archivematicaCommon/archivematicaFunctions.py", line 267, in get_dir_uuids
    dir_uuid, dir_)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 66: ordinal not in range(128)```

**Comment by lwo** [comment]
But this error message occurs even with the patch applied to qa/1.x. We merged it in our fork over here:
https://github.com/IISH/archivematica/commit/79d1b9bad6dab2e05b5b72f72ab8cc6edfd2a240

Did we miss something?

**Comment by kerim1** [comment]
Looking again at the provided log, it may not have been the backtick at all, but the next folder in the list to obtain an uuid. There is only one other folder in our test collection in the 'silly filenames' folder: https://github.com/IISH/archivematica-test-collections/tree/master/14%20-%20Silly%20filenames

**Comment by ross-spencer** [comment]
Hi @lwo and @kerim1 thanks for the extra debugging on this. As noted in the meeting earlier, this currently looks like it is a regression with some of the bigger changes in `qa/1.x`. The last commit that works for me is: https://github.com/artefactual/archivematica/commit/53167ee1a00745ca2a82dea9e636ab28be2bb173. We will investigate why there might be an issue with the current `qa` branch and understand what is needed to fix it asap.

**Comment by marktriggs** [comment]
Hi all,

@jhsimpson mentioned testing had found a bug while importing the "Silly filenames" collection from https://github.com/IISH/archivematica-test-collections/tree/master/14%20-%20Silly%20filenames, so we've been looking into that.

Testing locally, we saw a failure with filenames containing umlauts (like "Is % ! & foldër") that pops up when one of the now-UTF-8 format strings meets an argument that isn't UTF-8 encoded.  Like this:

```
        msg = u'Assigning UUID {} to directory path {}'.format(
            dir_uuid, dir_path)
```

In this case, dir_path isn't encoded as UTF-8, so there's a mismatch between the format string and the argument.  The same sort of issue that Ross identified in https://github.com/artefactual/archivematica/commit/bec08e35d53d4660ced1d178bcd94a595bb40285.  Converting the arguments to UTF-8 corrected that issue.

The other issue we saw was more thorny.  When a path contains a backtick character, the MCP Server escapes it by prepending a backslash.  Previously, this backslash would be removed when the string was passed to a shell command, but we don't do that anymore--now we use `shlex` to parse those command lines.

It turns out that `shlex` doesn't perfectly mirror bash escaping in this case.  Bash removes the backslash preceding the backtick, but `shlex` leaves it there, and that caused problems down the line.  Manually post-processing the output from shlex to handle this case fixed things up.  Testing all sorts of other funny cases didn't reveal any other edge cases that we could find.

We've sent a PR for these fixes (https://github.com/artefactual/archivematica/pull/1210) and combined with Joel's change from https://github.com/artefactual/archivematica/tree/dev/issue-16-job-encoding-bug  we're seeing those odd transfers running through now.

**Comment by peterVG** [comment]
Tested this successfully on AM 18x Bionic with a simple text file with two backticks in the title ("backtick \`test file\`.txt"). It passed the assign UUID microservices without error and the backticks were then removed and replaced with underscores in the "Clean up names" microservice. The backticks were then still present in the final AIP METS XML premis:originalName value. 

Is this sufficient for this fix or does it require further/different tests?

**Comment by ross-spencer** [comment]
Do you have a view @lwo or @kerim1? From our initial work on this, I think @peterVG's testing coversthe problems we were seeing, but let us know.

**Comment by peterVG** [comment]
FYI, I have since also tested with https://github.com/IISH/archivematica-test-collections/tree/master/14%20-%20Silly%20filenames and got the same successful results.

**Comment by sallain** [comment]
@ross-spencer Is there anything regarding name sanitization that we should be documenting better? I don't think that we have much on it in the docs and it's a common question in the forum/from clients.

**Comment by ross-spencer** [comment]
Hi @sallain. Some more information would be useful I did some testing and logged a few new issues. While doing that I wrote up a few suggestions as notes, but could be the basis for something more complete?:

## Sanitize Names

Archivematica groups heterogeneous tools together to create a preservation 
workflow. Because different tools are not always compatible with the same input 
values, a microservice called `sanitize names` is used early on in the 
processing of a collection to help reduce the number of errors which might arise 
across multiple different tools. 

Valid filename characters are determined by this code in Archivematica:

* https://github.com/artefactual/archivematica/blob/b6dcfb07a6be5957a5085efd1fecd8462fdc3a91/src/MCPClient/lib/clientScripts/sanitizeNames.py#L34

Which resolves to:

``-_.()abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789``

Filename characters will be replaced with the underscore character where the 
original is not found in the above list.

Example outputs of sanitize names may therefore be:

```
+-----------------+-----------------+--------------------------------------------------------------------------------------------------------------------------+
|  Original Name  | Normalized Name |                                                       METS Output                                                        |
+-----------------+-----------------+--------------------------------------------------------------------------------------------------------------------------+
| @file           | _file           | Original name="%transferDirectory%objects/@file"; cleaned up name="%transferDirectory%objects/_file"                     |
| file^           | fname-__        | Original name="%transferDirectory%objects/fname-~^"; cleaned up name="%transferDirectory%objects/fname-__"               |
| f & ile         | f___ile         | Original name="%transferDirectory%objects/f &amp; ile"; cleaned up name="%transferDirectory%objects/f___ile"             |
| Česká republika | Ceska_republika | Original name="%transferDirectory%objects/?eská republika"; cleaned up name="%transferDirectory%objects/Ceska_republika" |
| Éireann         | Eireann         | Original name="%transferDirectory%objects/Éireann"; cleaned up name="%transferDirectory%objects/Eireann"                 |
| España          | Espana          | Original name="%transferDirectory%objects/España"; cleaned up name="%transferDirectory%objects/Espana"                   |
| Ísland          | Island          | Original name="%transferDirectory%objects/Ísland"; cleaned up name="%transferDirectory%objects/Island"                   |
+-----------------+-----------------+--------------------------------------------------------------------------------------------------------------------------+
```

Additional information can be found in the complete PREMIS event, e.g.

```
  <premis:event xmlns:premis="info:lc/xmlns/premis-v2" xsi:schemaLocation="info:lc/xmlns/premis-v2 http://www.loc.gov/standards/premis/v2/premis-v2-2.xsd" version="2.2">
    <premis:eventIdentifier>
      <premis:eventIdentifierType>UUID</premis:eventIdentifierType>
      <premis:eventIdentifierValue>95b832bd-5541-4921-a70d-cbff24bc2f53</premis:eventIdentifierValue>
    </premis:eventIdentifier>
    <premis:eventType>name cleanup</premis:eventType>
    <premis:eventDateTime>2018-10-01T21:59:53.549040+00:00</premis:eventDateTime>
    <premis:eventDetail>prohibited characters removed:program="sanitize_names"; version="1.10.d0ccb7d7661cf35c769dcc0846d8f087998af713"</premis:eventDetail>
    <premis:eventOutcomeInformation>
      <premis:eventOutcome></premis:eventOutcome>
      <premis:eventOutcomeDetail>
        <premis:eventOutcomeDetailNote>Original name="%transferDirectory%objects/?eská republika"; cleaned up name="%transferDirectory%objects/Ceska_republika"</premis:eventOutcomeDetailNote>
      </premis:eventOutcomeDetail>
    </premis:eventOutcomeInformation>
    <premis:linkingAgentIdentifier>
      <premis:linkingAgentIdentifierType>preservation system</premis:linkingAgentIdentifierType>
      <premis:linkingAgentIdentifierValue>Archivematica-1.8</premis:linkingAgentIdentifierValue>
    </premis:linkingAgentIdentifier>
    <premis:linkingAgentIdentifier>
      <premis:linkingAgentIdentifierType>repository code</premis:linkingAgentIdentifierType>
      <premis:linkingAgentIdentifierValue>test</premis:linkingAgentIdentifierValue>
    </premis:linkingAgentIdentifier>
  </premis:event>
```

And also, the `cleanupnames.log` (`**`) file if you look through the directory 
tree of the AIP:

```
test-names-53f503c7-c802-4a9e-9d60-81920f99419c$ tree
.
├── bag-info.txt
├── bagit.txt
├── data
│   ├── logs
│   │   ├── fileFormatIdentification.log
│   │   ├── filenameCleanup.log **
│   │   └── transfers
│   │       └── test-names-d9674a55-0763-4de0-aceb-9736863821d0
│   │           └── logs
│   │               ├── fileFormatIdentification.log
│   │               └── filenameCleanup.log **
│   ├── METS.53f503c7-c802-4a9e-9d60-81920f99419c.xml
│   ├── objects
│   │   ├── Ceska_republika
│   │   ├── Eireann
│   │   ├── Espana
│   │   ├── _file
│   │   ├── f___ile
│   │   ├── fname-__
│   │   ├── Island
│   │   ├── metadata
│   │   │   └── transfers
│   │   │       └── test-names-d9674a55-0763-4de0-aceb-9736863821d0
│   │   │           └── directory_tree.txt
│   │   └── submissionDocumentation
│   │       └── transfer-test-names-d9674a55-0763-4de0-aceb-9736863821d0
│   │           └── METS.xml
│   └── README.html
├── manifest-sha256.txt
└── tagmanifest-md5.txt

11 directories, 19 files
```

**Comment by sallain** [comment]
@ross-spencer finally returning to this - thank you for this documentation! I will try to incorporate it into the docs because there's basically nothing there that describes this microservice.
