### ISSUE TITLE
Problem: Failure to match in ArchivesSpace DIP Upload shows as success in Dashboard

### ISSUE THREAD

**Issue by bonniegee** [archivematica/Issues#258]
**Expected behaviour**
Using the ArchivesSpace DIP Upload workflow, I expect the dashboard to show a failure (or at least a warning) for the Job Upload to ArchivesSpace when the pairing fails for a file.

**Current behaviour**
I included an archivesspaceids.csv with a transfer and set the Processing Configuration to automatically "Upload DIP to ArchivesSpace." The archivesspaceids.csv contained incorrect filenames. When Job Upload to ArchivesSpace completed it showed as successful; it also seemed successful on the tasks page for the job. When I checked MCPclient.debug.log, I saw warnings for the task:

```
11518:WARNING   2018-10-10 14:28:14  __main__:upload-archivesspace:upload_to_archivesspace:79:  Skipping file /var/archivematica/sharedDirectory/watchedDirectories/uploadDIP/testWarningMessage-a111f871-d06d-4c99-95f0-eac5cc6f45ac/objects/7a452894-c26d-4846-99f2-4c85ad3e3528-25d168d667c74ddd9e7e8a0ab7b7e8ae_002r.jpg (7a452894-c26d-4846-99f2-4c85ad3e3528) - no pairing found
11519:WARNING   2018-10-10 14:28:14  __main__:upload-archivesspace:upload_to_archivesspace:79:  Skipping file /var/archivematica/sharedDirectory/watchedDirectories/uploadDIP/testWarningMessage-a111f871-d06d-4c99-95f0-eac5cc6f45ac/objects/e3187016-0038-4994-a518-54a52209a3bc-25d168d667c74ddd9e7e8a0ab7b7e8ae_002v.jpg (e3187016-0038-4994-a518-54a52209a3bc) - no pairing found
```

**Steps to reproduce**
1. In the Processing Configuration, select "Upload DIP to ArchivesSpace" for the "Upload DIP" decision.
2. Ingest a transfer with an archivesspaceids.csv file that contains incorrect filenames or filepaths.
3. When Job Upload to ArchivesSpace  is complete, review tasks page in dashboard and MCPclient.log

**Your environment (version of Archivematica, OS version, etc)**
Archivematica 1.7.2

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by ross-spencer** [comment]
Logging only in the MCPClient.log looks like to be fixed in `1.9' as you can see in my screenshot below the logging appears as expected in the `stderr`:

![image](https://user-images.githubusercontent.com/1880412/58559525-96fadd00-8223-11e9-88be-3c9c1858fdf4.png)

This is likely fixed via: https://github.com/artefactual/archivematica/commit/94d7275deb05cf92e3b4eba98b799ef5983f0137#diff-8ff1a676511770637e5266ee869be540

But perhaps this needs verification once folks have upgraded and attempt the same task. 

I will ask in this ticket for further clarification for this particular task, but the rationale for a job not 'failing' may be that partial success may still be more desirable (robustness principle?) than failure where those failures are not critical and can be managed in different ways.

That being said, as part of looking in to this today, I wonder if there are strategies that Archviematica can adopt. I have a few ideas but these will all need careful consideration. I'll get back to you on those asap. 

I have a question: How would you normally approach rectifying a situation like this where my (naive?) assumption is that some files make it to ArchivesSpace and some don't? Would you be able to document that procedure for this ticket?

**Comment by bonniegee** [comment]
Thanks @ross-spencer - I just ran a test through our development instance (which is on 1.9.1), and I can now see the warnings in the `stderr` 🎉

I think there are three components (well, now two) when this happens:
1. There are no visual (or other) cues in the Archivematica dashboard that a DAO was not successfully created in ArchivesSpace; I didn't notice missing DAOs until reviewing the finding aid they were supposed to be uploaded to
2. Troubleshooting required logging into the server to access the logs (this is fixed!)
3. Our solution when a DAO is not created by Archivematica is to create it manually

My main concern about the above is primarily around scaling ingests.

The vast majority of what we've been ingesting the past few months has had one access file per SIP, so we have not run into an instance where some files uploaded successfully, and others didn't.

I'll also note that this is for when the ArchivesSpace DIP upload doesn't fully work because of an issue with the archivesspaceids.csv file--a failure due to an ArchivesSpace timeout means the Job Upload to ArchivesSpace fully fails.

I wonder if #563 is related?

**Comment by sromkey** [comment]
@evelynPM would you be able to test and see if this is still an issue?

**Comment by evelynPM** [comment]
This is still happening. The dashboard says "Job: Upload to ArchivesSpace completed successfully", but the tool output shows the following:

`upload-archivesspace_v0.0: WARNING   2019-11-13 17:51:28,681  clientScripts.upload_archivesspace.upload_to_archivesspace:102  Skipping file /var/archivematica/sharedDirectory/watchedDirectories/uploadDIP/ASpace_test-cf1dfde8-d4b4-429a-9e18-9647646813f9/objects/758e079a-aaf7-4391-95c2-f21cbe2b3d7d-Landing_zone.jpg (758e079a-aaf7-4391-95c2-f21cbe2b3d7d) - no pairing found
upload-archivesspace_v0.0: WARNING   2019-11-13 17:51:28,686  clientScripts.upload_archivesspace.upload_to_archivesspace:102  Skipping file /var/archivematica/sharedDirectory/watchedDirectories/uploadDIP/ASpace_test-cf1dfde8-d4b4-429a-9e18-9647646813f9/objects/6f4165de-bc19-4a0a-b029-ecd806a7ce1c-WFPC01.jpg (6f4165de-bc19-4a0a-b029-ecd806a7ce1c) - no pairing found`

**Comment by sromkey** [comment]
@replaceafill could you give us a size on this?

**Comment by replaceafill** [comment]
I think the problem here is that [the call to the function doing the upload](https://github.com/artefactual/archivematica/blob/48bbc048d380022a607b8042c1f360c718218dfa/src/MCPClient/lib/clientScripts/upload_archivesspace.py#L310-L324) in this script doesn't affect the job status.

Maybe we could move it to the [`try` block](https://github.com/artefactual/archivematica/blob/48bbc048d380022a607b8042c1f360c718218dfa/src/MCPClient/lib/clientScripts/upload_archivesspace.py#L299-L302) and change it so it records if [any file couldn't be paired](https://github.com/artefactual/archivematica/blob/48bbc048d380022a607b8042c1f360c718218dfa/src/MCPClient/lib/clientScripts/upload_archivesspace.py#L101-L103) and raise an exception accordingly at the end. We should also try to handle any errors raised by the [`add_digital_object` call to the ArchivesSpaceClient](https://github.com/artefactual/archivematica/blob/48bbc048d380022a607b8042c1f360c718218dfa/src/MCPClient/lib/clientScripts/upload_archivesspace.py#L213-L232).

One thing I didn't understand is the [deletion of pairs **on each file iteration**](https://github.com/artefactual/archivematica/blob/48bbc048d380022a607b8042c1f360c718218dfa/src/MCPClient/lib/clientScripts/upload_archivesspace.py#L234)? Couldn't that be done at the end?

**Comment by replaceafill** [comment]
@sromkey @evelynPM I tested this today with our ArchiveSpace instance and just wanted to confirm our plan.

The dashboard currently shows the warnings when files cannot be paired:

![Screenshot_2019-12-06 Archivematica Dashboard -](https://user-images.githubusercontent.com/560781/70336829-7b464400-180f-11ea-8715-00145f1ccfc6.png)

and it shows the `Upload to ArchivesSpace` job as successful under that condition:

![Screenshot_2019-12-06 Archivematica Dashboard - Ingest](https://user-images.githubusercontent.com/560781/70336869-90bb6e00-180f-11ea-9ef5-e51ae4927eec.png)

What we want is: if any file cannot be pair the workflow should continue (as it does now) but the job should be marked as failed (red in the UI).

Did it get it right?

**Comment by sromkey** [comment]
@replaceafill Yes I think that is right!

**Comment by sallain** [comment]
If `Upload DIP to ArchivesSpace` can't match an object, the job now shows as failed and goes pink.

![Screenshot of Archivematica Dashboard - Ingest.jpg](https://codetreeusercontent.s3.amazonaws.com/uploads/4d31ec4c-2cee-42e4-928a-49488ffd2301/Screenshot+of+Archivematica+Dashboard+-+Ingest.jpg)

However, it does not show up in the failure report and a failure email isn't sent. These things weren't really discussed in the scope of the fix above, so I suggest we make a new issue to address that and call this one complete.

**Comment by sallain** [comment]
I've created a new issue about general failure reporting behaviour here: #1114
